apiVersion: v1
kind: Service
metadata:
  name: express-pss-denormalizer-service
  labels:
    app: express-pss-denormalizer
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: express-pss-denormalizer
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}