apiVersion: v1
kind: Service
metadata:
  name: express-pss-denormalizer-service
  labels:
    app: express-pss-denormalizer
spec:
  type: LoadBalancer
  selector:
    app: express-pss-denormalizer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000