apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-pss-denormalizer-deployment
  labels:
    app: express-pss-denormalizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-pss-denormalizer
  template:
    metadata:
      labels:
        app: express-pss-denormalizer
    spec:
      containers:
      - name: express-pss-denormalizer
        image: localhost:5000/express-pss-denormalizer:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: express-pss-denormalizer-secret
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
